import '@/styles/globals.css';
import type { Metadata } from 'next';
import { MontserratFont, Quicksand_font } from '@/lib/font_imports';

import { ClerkProvider } from '@clerk/nextjs';

import Logo from '@/components/navigation/Logo';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AppLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html
        lang='en'
        className={`${MontserratFont.variable} ${Quicksand_font.variable}`}
      >
        <body className='flex flex-col lg:grid-cols-12 lg:grid lg:auto-rows-min h-screen'>
          <header className='lg:row-start-1 lg:col-span-full lg:self-start px-4 py-5 border-b-2 border-greylight flex justify-between items-center'>
            <Logo />
          </header>
          <main className='h-screen lg:row-start-2 lg:col-start-3 lg:col-end-13 p-8 overflow-y-scroll'>
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
