import '@/styles/globals.css';
import type { Metadata } from 'next';
import { MontserratFont, Quicksand_font } from '@/lib/font_imports';

import { ClerkProvider } from '@clerk/nextjs';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Home({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html
        lang='en'
        className={`${MontserratFont.variable} ${Quicksand_font.variable}`}
      >
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
