import '@/styles/globals.css';
import type { Metadata } from 'next';
import { MontserratFont, Playfair } from '@/lib/font_imports';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className={`${MontserratFont.variable} ${Playfair.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
