import '@/styles/globals.css';
import type { Metadata } from 'next';
import { MontserratFont, Quicksand_font } from '@/lib/font_imports';
import Logo from '@/components/navigation/Logo';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function OnBoardingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <header className='px-4 py-5 border-b-2 border-greylight flex justify-between items-center'>
        <Logo />
      </header>
      <main className='h-screen lg:row-start-2 lg:col-start-3 lg:col-end-13 p-8 overflow-y-scroll'>
        {children}
      </main>
    </>
  );
}
